#!/sbin/openrc-run
# Copyright 2018 Gentoo Foundation

start() {
	ebegin "Starting radeon profile daemon"
	start-stop-daemon \
		--start \
		--make-pidfile \
		--pidfile /var/run/radeon-profile-daemon.pid \
		--background \
		--exec /usr/bin/radeon-profile-daemon
	eend $?
}

stop() {
	ebegin "Stopping radeon profile daemon"
	start-stop-daemon --stop --signal 15 \
			--pidfile /var/run/radeon-profile-daemon.pid
	eend $?
}
